version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  run_build:
   docker:
     - image: circleci/node:16
   steps:
     - checkout
     - run:
        name: install npm dependencies
        command:
          npm install 
     - run:
        name: run build
        command:
          npm run build
workflows:
  build-test-and-deploy-to-heroku:
    jobs:
      - run_build
      - heroku/deploy-via-git:
         requires:
           - run_build
         filters:
          branches:
            only: main